services:
  postgres:
    image: postgres:17
    restart: always
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "sales_insight_admin"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"